Repository WeBankFinTech/WeEvent, pull requests merged in 2019-07, with the labels that each got.

#83 fix the list subscribe
  weevent-broker/src/main/java/com/webank/weevent/protocol/rest/AdminRest.java
Labels: bug

#85 add pressure measurement script and fix the stomp bugs
  weevent-broker/src/main/java/com/webank/weevent/protocol/stomp/BrokerStomp.java
  weevent-broker/src/test/java/com/webank/weevent/pressureMeasurement/jmeterScript.jmx
  weevent-broker/src/test/java/com/webank/weevent/sample/Stomp.java
  weevent-client/src/main/java/com/webank/weevent/sdk/jms/WebSocketTransport.java
Labels: bug, enhancement

#84 use 'try with resource' to resolve connection and statement close
  weevent-governance/src/main/java/com/webank/weevent/governance/initial/InitialDb.java
Labels: bug

#87 ignore npm build librarys
  .gitignore
Labels: good first issue

#89 remove ssl support and relative config
  weevent-broker/src/main/java/com/webank/weevent/broker/config/WeEventConfig.java
  weevent-broker/src/main/java/com/webank/weevent/broker/fisco/util/SystemInfoUtils.java
  weevent-broker/src/main/java/com/webank/weevent/broker/ha/MasterJob.java
  weevent-broker/src/main/java/com/webank/weevent/protocol/mqttbroker/BrokerServer.java
  weevent-broker/src/main/java/com/webank/weevent/protocol/rest/AdminRest.java
Labels: good first issue

#97 update quickinstall broker and nginx listen port
  weevent-build/check-service.sh
  weevent-build/config.properties
  weevent-build/package.sh
Labels: good first issue
